- name: install web servers
  hosts: all
  become: true
  tasks: 
    - name: Install the latest version of Apache on Ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"
        
    - name: Install the latest version of Apache on RedHat
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"